[build]
    functions = "functions"
[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200

[[redirects]]
    from = "/graphql"
    to = "https://graphql.fauna.com/graphql"
    status = 200
    force = true # COMMENT: ensure that we always redirect
    headers = { authorization = "Bearer FAUNADB_SERVER_SECRET"}